### ISSUE TITLE
Investigar la mejor forma de subir imagenes en el alta y modificacion de adsorbatos y adsorbentes

### ISSUE THREAD

**Issue by Santiago-Pinto** [Reactor-Army/reactor_backend1#66]
Encontrar una forma de hacerlo y poner un ejemplo. Explicar cual alternativa es mejor

**Comment by MatiasReimondo** [comment]
Bueno despues de buscar varios ejemplos, encontré que hay una manera estándar de hacerlo, básicamente usando form-data del lado de react y ModelAttribute con multipart form data en Spring Boot.
Los mejores articulos que encontre sobre esto son dos de stackoverflow que explican todo
https://stackoverflow.com/questions/49845355/spring-boot-controller-upload-multipart-and-json-to-dto (Ejemplo completo del back)
https://stackoverflow.com/questions/60111117/react-spring-boot-upload-file-and-form-data (Front)

https://www.devglan.com/react-js/file-upload-react-spring-rest

Abajo dejo ejemplo del back y front, capaz dejo varios del front

**Comment by MatiasReimondo** [comment]
BACKEND

@RequestMapping(path = "/{groupId}", method = RequestMethod.POST,
        consumes = {"multipart/form-data"})
public ExpenseSnippetGetDto create(@ModelAttribute ExpensePostDto expenseDto, @PathVariable long groupId, Principal principal) throws IOException {
   //...
}

Aca lo importante es @ModelAtributte y la annotation arriba del endpoint que indica que consume form-data

Obviamente hay una clase que adentro tiene:

public class ExpensePostDto extends ExpenseBaseDto {

    private MultipartFile image;

    private String description;

    private List<Long> sharers;

}

**Comment by MatiasReimondo** [comment]
https://stackoverflow.com/questions/41610811/react-js-how-to-send-a-multipart-form-data-to-server
